### ISSUE TITLE
Offer the ability to use grunt-download-electron instead of grunt-build-atom-shell

### ISSUE THREAD

**Issue by almathie** [atom-archive/electron-starter#83] opened 2015-05-08 00:15 UTC
Quite a lot here are linked to the infamous build-atom-shell grunt task.
See :
https://github.com/atom/electron-starter/issues/69
https://github.com/atom/electron-starter/issues/77
https://github.com/atom/electron-starter/issues/54

Besides the issues some people are facing, this task is slow.
The last time I needed to add a package to the manifest, it took more than 8 hours to complete
I have a bad connection and all, but still.

The build atom-shell task seems only needed to generate a "binary" of the electron app.
This could be replaced by "gunt-download-electron" which would fetch (and cache!) the binary.

As @kakaol mentioned here : https://github.com/atom/electron-starter/issues/71 the build step seems needed for the icon and the executable. For deployment/release this is important. In "dev mode" I would happily trade an executable name and an icon if this allowed me to iterate more quickly.

So, would it be feasible to have an optional --dev switch on the build (and run ?) task to use the downlad grunt task instead of the build one.

**Comment by paulcbetts** [comment] 2015-05-08 00:47
The problem is until recently, `grunt-download-electron` was production usable on all platforms literally only for Atom itself. This is recently no longer the case, so I'll probably switch to using `grunt-download-electron` instead

**Comment by jgeurts** [comment] 2015-05-22 16:07
Would love to see this functionality... the build-atom-shell task is painful

**Comment by westoque** [comment] 2015-06-03 08:36
:+1: same here. painful waiting for build-atom-shell task to complete.

**Comment by lllama** [comment] 2015-06-28 16:13
This could probably help with development under Windows as well given that the electron build fails.

**Comment by lee-dohm** [comment] 2018-04-25 17:30
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-25 17:30 UTC
